#ifndef MACROS_H_INCLUDED
#define MACROS_H_INCLUDED

#define MAX_SENSORS 20

#define SENSOR_CODE_MAX_LENGTH 8

#define SENSOR_STATE_MAX_LENGTH 12

#define SENSOR_TEMPERATURE_MAX_LENGTH 6

#define SENSOR_UNIX_TIMESTAMP_MAX_LENGTH 12

#define MAX_LINE_LENGTH SENSOR_CODE_MAX_LENGTH\
     + SENSOR_STATE_MAX_LENGTH\
     + SENSOR_TEMPERATURE_MAX_LENGTH\
     + SENSOR_UNIX_TIMESTAMP_MAX_LENGTH

#endif // MACROS_H_INCLUDED
